### ISSUE TITLE
ImportError: DLL load failed while importing core: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by NameLacker** [PaddlePaddle/Quantum#11]
paddlepaddle: 2.1.2
paddle-quantum: 2.1.2
system: win10

报错：
Traceback (most recent call last):
  File "D:\anaconda\envs\paddle21\lib\site-packages\psi4\__init__.py", line 55, in <module>
    from . import core
ImportError: DLL load failed while importing core: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Base_project/neural-network-base/quantum_computing/quantum_simulation/structure_of_hamiltonian.py", line 15, in <module>
    from paddle_quantum.qchem import geometry, get_molecular_data
  File "D:\anaconda\envs\paddle21\lib\site-packages\paddle_quantum\qchem.py", line 22, in <module>
    import psi4
  File "D:\anaconda\envs\paddle21\lib\site-packages\psi4\__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: DLL load failed while importing core: 动态链接库(DLL)初始化例程失败。

**Comment by wangzihe1996** [comment]
这个的话，你当前的Python环境下有安装`Psi4`吗？没有的话，需要先安装这个包，具体的安装方式可以参考量桨的[readme](https://github.com/PaddlePaddle/Quantum/blob/master/README_CN.md#%E9%87%8F%E5%AD%90%E5%8C%96%E5%AD%A6%E6%A8%A1%E5%9D%97%E7%9A%84%E7%8E%AF%E5%A2%83%E8%AE%BE%E7%BD%AE)。
